### ISSUE TITLE
Incompatible with pnpm v3

### ISSUE THREAD

**Issue by lo1tuma** [adisbladis/pnpm2nix#10]
I just wanted to give pnpm and pnpm2nix a try and figured out that pnpm2nix doesn’t work with the current version of pnpm v3.0.1 (which is in nixpkgs-unstable `nodePackages-10_x.pnpm`).

It seems like the lock file changed. The file is now named `pnpm-lock.yaml` instead of `shrinkwrap.yaml`. When I specify the new filename in the `shrinkwrapYML` option then I get an error because of an failed assertion, expecting the `shrinkwrapVersion` to be `3` but in the lock file the `lockfileVersion` is `5`.

**Comment by adisbladis** [comment]
Thanks for reporting! I'll try to have a look at this in the next couple of days.

**Comment by adisbladis** [comment]
I have pushed my current progress to the branch `pnpm-3`.
The only thing left is fixing up the recursive test.

**Comment by adisbladis** [comment]
I just merged the `pnpm-3` branch even though it has a known regression, namely pnpm workspaces support is lacking.

**Comment by baracoder** [comment]
It breaks again:
I have just created a lock file with latest `nodePackages_10_x.pnpm`, the lockfile version is now `5.1` which fails an assertion
